[default]

LOGS_PATH = 'logs/logs.txt'
TEMP_INCOMING_AUDIO_PATH = "data/files/audios/temp_audios"
TEMP_OUTGOING_AUDIO_PATH = "data/files/audios/temp_audios"
CHAT_HISTORY_PATH = "data/files/chat_history"
AUDIO_STREAM_SAMPLE_RATE_HERTZ = 16000
SERVER_IP = "localhost"
SERVER_PORT = 5011
SERVER_FILES_IP = "http://localhost:5011"
CLIENT_SQL_CSV_PATH = "data/files/queries/client_sql.csv"
METADATA_PATH = "data/files/queries/tables_metadata.txt"
